region: eu-central-1
poll_interval_secs: 20
targets:
  - name: debot00
    instance_id: i-0c08fba996bc21879
    service: debot00
    status_path: /home/ec2-user/debot_status/debot00/status.json
  - name: debot01
    instance_id: i-0c08fba996bc21879
    service: debot01
    status_path: /home/ec2-user/debot_status/debot01/status.json
# auth:
#   username: admin
#   password: change-me
